import type { FrameSpec, InlineGroup, InlineSpec, PreviewSpec, Tone } from "./types";

const inline = (
  group: InlineGroup,
  tone: Tone,
  extra: Omit<InlineSpec, "kind" | "group" | "tone"> = {},
): InlineSpec => ({ kind: "inline", group, tone, ...extra });

const frame = (
  tone: Tone,
  width: number,
  height: number,
  extra: Omit<FrameSpec, "kind" | "tone" | "viewport"> = {},
): FrameSpec => ({ kind: "frame", tone, viewport: { width, height }, ...extra });

/**
 * How every component is previewed. One map, used by the index, the expanded
 * view, the component page and the iframe route, so a component cannot have a
 * preview in one place and not another. `scripts/check-previews.mjs` fails the
 * build if a registry slug is missing here or has no render.
 */
export const specs: Record<string, PreviewSpec> = {
  "glass-button": inline("basic", "void"),
  card: inline("basic", "void"),
  input: inline("basic", "void"),
  "text-input": inline("basic", "paper"),
  "radio-group": inline("basic", "paper"),
  checkbox: inline("basic", "paper"),
  "dob-picker": inline("basic", "paper"),
  "select-input": frame("paper", 420, 280),
  "file-upload": inline("basic", "paper"),
  stepper: inline("basic", "paper"),
  "stepper-navigation": inline("basic", "paper"),
  "submission-loader": frame("paper", 600, 400),
  "screen-layout": frame("paper", 720, 480),
  "typewriter-loader": inline("basic", "paper"),
  "toast-container": frame("paper", 480, 320),
  "toolbar-button": inline("basic", "paper"),
  "collapsible-sidebar": inline("basic", "paper"),
  "side-panel": inline("basic", "paper"),
  "node-card": inline("basic", "paper"),
  "tubelight-navbar": inline("motion", "void"),
  "md3-switch": inline("basic", "paper"),
  "dual-confirm-dialog": frame("paper", 600, 400),
  "blender-upload": inline("basic", "paper", { fit: 340 }),
  "empty-state": inline("basic", "paper", { fit: 420 }),
  "checkbox-variants": inline("basic", "paper"),
  "loading-spinner": inline("basic", "paper"),
  "price-breakdown": inline("basic", "paper"),
  pagination: inline("basic", "paper", { fit: 460 }),
  "custom-cursor": frame("void", 840, 560, { hint: "Move" }),
  preloader: frame("paper", 720, 480),
  "site-header": frame("void", 800, 533, { hint: "Hover" }),
  "mobile-menu": frame("void", 390, 560),
  "elastic-line-divider": inline("basic", "void", { hint: "Hover" }),
  "circle-cta": inline("gsap", "void", { hint: "Hover" }),
  "image-reveal": inline("gsap", "void", { replay: true }),
  "featured-project-card": frame("void", 1000, 667),
  "project-card": inline("basic", "void", { fit: 560 }),
  marquee: inline("gsap", "void"),
  "contact-section": frame("void", 960, 640, { hint: "Move" }),
  "text-disperse-link": inline("gsap", "void", { hint: "Hover" }),
  "image-with-fallback": inline("basic", "paper"),
  "skeleton-card": inline("basic", "paper"),
  "ecom-empty-state": inline("motion", "paper", { fit: 420 }),
  breadcrumb: inline("basic", "paper"),
  "category-chips": inline("motion", "paper"),
  "category-grid": frame("paper", 420, 280),
  "search-overlay": frame("paper", 420, 280),
  "mobile-bottom-nav": frame("paper", 390, 260),
  "product-card": inline("motion", "paper", { fit: 380 }),
  "sticky-cart-bar": frame("paper", 390, 260),
  "app-header": frame("paper", 800, 533),
  "bakery-product-card": inline("basic", "paper", { fit: 440 }),
  "testimonial-card": inline("basic", "paper"),
  "faq-accordion": inline("basic", "paper", { fit: 600 }),
  "whatsapp-fab": frame("paper", 390, 260, { hint: "Hover" }),
  "image-placeholder": inline("basic", "paper"),
  "sticky-navbar": frame("paper", 390, 260),
  "error-boundary": frame("paper", 600, 400),
  "sticky-nav": frame("paper", 600, 400),
  "use-theme-ripple": frame("paper", 600, 400, { hint: "Click" }),
  "shiny-badge": inline("basic", "paper"),
  "border-beam-button": inline("basic", "paper"),
  "typing-hero": frame("paper", 900, 600, { replay: true }),
  "feature-card-grid": inline("basic", "paper", { fit: 640 }),
  "numbered-steps-list": inline("basic", "paper", { fit: 560 }),
  "formula-block": inline("basic", "paper", { fit: 460 }),
  "signal-card-grid": inline("basic", "paper", { fit: 640 }),
  "principle-card-grid": inline("basic", "paper", { fit: 760 }),
  "diagnostic-grid": inline("basic", "paper", { fit: 600 }),
  "callout-box": inline("basic", "paper", { fit: 480 }),
  checklist: inline("basic", "paper", { fit: 440 }),
  "scroll-reveal": inline("basic", "paper", { replay: true }),
  "site-footer": inline("basic", "paper", { fit: 900 }),
  "depth-text": inline("basic", "void", { hint: "Move" }),
  magnet: inline("basic", "void", { hint: "Move near" }),
  "glare-hover": inline("basic", "void", { hint: "Hover" }),
  "cinematic-water-background": inline("basic", "void"),
  "conic-border-button": inline("basic", "void"),
  "pointer-glow-card": inline("basic", "paper", { hint: "Hover" }),
  "shiny-gradient-text": inline("basic", "void"),
  "blur-in-reveal": inline("basic", "paper", { replay: true }),
  "section-progress-rail": inline("basic", "void"),
  "edge-fade-marquee": inline("basic", "void"),
  "parallax-product-stage": inline("gsap", "void", { fit: 600, replay: true, hint: "Move" }),
  "stagger-blur-text": inline("basic", "paper", { replay: true }),
  "animated-gradient-rule": inline("basic", "void"),
  "jewelry-cursor": frame("cream", 600, 400, { hint: "Move" }),
  "scroll-unfurl-preloader": frame("void", 720, 480),
  "foil-specular-card": inline("basic", "void", { fit: 380, hint: "Move" }),
  "wax-seal-button": inline("gsap", "void", { hint: "Hover" }),
  "canvas-petal-field": inline("basic", "void"),
  "film-grain-overlay": inline("basic", "void"),
  "scratch-foil-reveal": inline("basic", "void", { hint: "Scratch", replay: true }),
  "pixel-demorph-image": inline("basic", "void", { replay: true }),
  "scroll-parallax-layer": inline("gsap", "void", { hint: "Scroll" }),
  "till-receipt-print": inline("basic", "cream", { fit: 380, replay: true }),
  "magic-rings": inline("three", "void", { hint: "Move" }),
  "star-border": inline("basic", "cream"),
  "shiny-text": inline("motion", "cream"),
  "circular-text": inline("motion", "cream", { hint: "Hover" }),
  "pinched-button": inline("basic", "cream"),
  "multi-step-loader": frame("paper", 720, 480),
  "metallic-logo-shimmer": inline("basic", "cream"),
  highlighter: inline("motion", "paper", { replay: true }),
  "text-type": inline("gsap", "paper"),
  "celebration-overlay": frame("paper", 640, 427),
  "damask-tile-backdrop": frame("cream", 600, 400),
};

export const frameSlugs = Object.entries(specs)
  .filter(([, s]) => s.kind === "frame")
  .map(([slug]) => slug);
